### ISSUE TITLE
Add sticky navbar.

### ISSUE THREAD

**Issue by padmajabhol** [threefreespirited/Jssconnect#15] opened 2021-03-09 09:16 UTC
The existing navbar disappears as we scroll down, I want to fix it.

**Comment by srk224** [comment] 2021-03-09 11:20
Hey
I would like to work on this issue. Can you please assign it to me under gssoc'21?
I have experience in web-dev and I will be able to do it.

**Comment by Kritikaagra** [comment] 2021-03-09 14:13
Hey...
I would like to fix this issue under GGSOC'21 ...plz assign this to me... Thank you

**Comment by padmajabhol** [comment] 2021-03-09 14:29
Guys, I m not the project admin.

**Comment by heysujal** [comment] 2021-03-09 19:54
Please provide details of the issue .Where does it disappear ? On which page?
Attach screenshots or video to illustrate the same.

**Comment by Aanchal116** [comment] 2021-03-10 05:27
Hii , 
I would like to work on this issue as a part of GSSOC'21. I've hands-on practice in web development and also a mentorship experience. Please assign this task to me if possible.

**Comment by AMAN123956** [comment] 2021-03-10 13:06
@padmajabhol  I am assigning this task to you give me an update within 3 days otherwise I will be assigning it to some other person

**Comment by padmajabhol** [comment] 2021-03-10 13:43
> @padmajabhol  I am assigning this task to you give me an update within 3 days otherwise I will be assigning it to some other person

![IMG_20210310_120443_896.jpg](https://user-images.githubusercontent.com/75530516/110638511-aa96ee00-81d4-11eb-8589-57bb7e6b3647.jpg)
But can you please help me with this? I can't load the live server.

**Comment by AMAN123956** [comment] 2021-03-10 14:05
After cloning the file just run nom install and then nodemon app.js

**Comment by Kritikaagra** [comment] 2021-03-10 15:40
@padmajabhol r u able to load the live server...because it shows the same error to me.

**Comment by AMAN123956** [comment] 2021-03-10 15:42
After cloning the repo run npm install command once all dependencies are
installed run node app.js

**Comment by Kritikaagra** [comment] 2021-03-10 15:47
@AMAN123956  I tried that too.... but its not working, error related to .env file is shown

**Comment by AMAN123956** [comment] 2021-03-10 15:54
Share screenshot of errors u are getting

**Comment by Kritikaagra** [comment] 2021-03-10 15:56
![image](https://user-images.githubusercontent.com/78923214/110657851-3154c680-81e7-11eb-8b98-e0bd9a33565a.png)
@AMAN123956

**Comment by AMAN123956** [comment] 2021-03-10 15:58
See our .env.example file to solve this issue

**Comment by AMAN123956** [comment] 2021-03-10 15:59
Moreover keep .env outside of views folder it seems that it is inside views
folder

**Comment by Kritikaagra** [comment] 2021-03-10 16:34
![image](https://user-images.githubusercontent.com/78923214/110663419-6dd6f100-81ec-11eb-932d-db8df85753ef.png)
Now its shows serving at port 3000 but chrome is not able to load site

**Comment by AMAN123956** [comment] 2021-03-10 16:44
Make sure ur computer is connected to internet and localhost:3000 is the
port on Google Chrome

**Comment by harshit9270** [comment] 2021-03-13 03:46
This is not a bug , the navbar reappears when you scroll down a bit more. This was intentional .

**Closed as completed by harshit9270** 2021-03-13 03:46 UTC
Labels: question, gssoc21
